/* GENERATED by build.js on 2026-10-05 — don't edit by hand.
   To change a project, edit its info.json and run: node build.js */
window.PROJECTS = [
  {
    "slug": "cooperatieve-kansenkaart",
    "title": "Coöperatieve Kansenkaart",
    "year": 2026,
    "categories": [
      "Stedenbouw",
      "Onderzoek"
    ],
    "place": "Rotterdam",
    "client": "Gemeente Rotterdam, ministerie van VRO (Atlas van Mogelijkheden)",
    "color": "#1e5a2a",
    "summary": "Werksessie en kaart: waar coöperatief wonen kan bijdragen aan het verbeteren van vier Rotterdamse wijken.",
    "downloads": [],
    "url": "projects/cooperatieve-kansenkaart/index.html",
    "thumbnail": "projects/cooperatieve-kansenkaart/thumbnail.jpg"
  },
  {
    "slug": "kaart-van-het-woonbeleid",
    "title": "Kaart van het Woonbeleid",
    "year": 2026,
    "categories": [
      "Onderzoek"
    ],
    "place": "Nederland",
    "client": "",
    "color": "#231f20",
    "summary": "Een overzicht van alle wetten en regels die raken aan de brede woonopgave in Nederland, met een rondleiding in het Nederlands en Engels.",
    "downloads": [],
    "url": "projects/kaart-van-het-woonbeleid/index.html",
    "thumbnail": "projects/kaart-van-het-woonbeleid/thumbnail.jpg"
  },
  {
    "slug": "beter-benutten-bestaande-rijtjeswoningen",
    "title": "Beter benutten bestaande rijtjeswoningen",
    "year": 2025,
    "categories": [
      "Architectuur",
      "Stedenbouw",
      "Onderzoek",
      "Publicatie"
    ],
    "place": "Nederland",
    "client": "College van Rijksbouwmeester en Rijksadviseurs",
    "color": "#2f8a35",
    "summary": "Kansen voor woningdelen, woningsplitsen en kleinschalig inbreiden in buurten met rijtjeswoningen uit de jaren ’60, ’70 en ’80.",
    "downloads": [
      {
        "label": "Volledig boek (PDF, 69 MB)",
        "file": "projects/beter-benutten-bestaande-rijtjeswoningen/beter-benutten-bestaande-rijtjeswoningen.pdf"
      }
    ],
    "url": "projects/beter-benutten-bestaande-rijtjeswoningen/index.html",
    "thumbnail": "projects/beter-benutten-bestaande-rijtjeswoningen/thumbnail.jpg"
  },
  {
    "slug": "ddw-eindhoven",
    "title": "De toekomst is al gebouwd!",
    "year": 2025,
    "categories": [
      "Architectuur",
      "Tentoonstelling"
    ],
    "place": "Eindhoven",
    "client": "Dutch Design Week 2025",
    "color": "#d2247d",
    "summary": "Een straatprofiel voor Dutch Design Week: ruimte voor 4 miljoen extra woningen door transformatie, woningdelen, optoppen, renovatie en verdichten.",
    "downloads": [],
    "url": "projects/ddw-eindhoven/index.html",
    "thumbnail": "projects/ddw-eindhoven/thumbnail.jpg"
  },
  {
    "slug": "goed-wonen-in-de-binnenstad",
    "title": "Goed Wonen in de Binnenstad",
    "year": 2025,
    "categories": [
      "Stedenbouw",
      "Onderzoek",
      "Publicatie"
    ],
    "place": "Nederland",
    "client": "City Deal Dynamische Binnensteden",
    "color": "#1f9945",
    "summary": "Ontwerpvoorstel van Platform Woonopgave voor de veerkrachtige binnenstad: vier doelgroepen, een actieagenda in tien punten en tien projecten.",
    "downloads": [],
    "url": "projects/goed-wonen-in-de-binnenstad/index.html",
    "thumbnail": "projects/goed-wonen-in-de-binnenstad/thumbnail.jpg"
  }
];
